services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.6.13@sha256:9b13386276490c41faf41fbe7f477964d2a6ba95dd087e7d22a890a65e58c841
    restart: unless-stopped
    ports:
      - "${DOZZLE_WEB_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_APPDATA_ROOT}/dozzle:/data
    environment:
      - TZ=${TZ}
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
