services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.5.2@sha256:2d0d65846bc436861aaf4053ece35a9cffef8d3501c58711f8cc4a3687ad8273
    restart: unless-stopped
    ports:
      - "${DOZZLE_WEB_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_APPDATA_ROOT}/dozzle:/data
    environment:
      - TZ=${TZ}
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
