services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.7.5@sha256:0ecac18a3491962002e9d6b9f9a363155131a4213e723ab86fc76dfee6e3cd8e
    restart: unless-stopped
    ports:
      - "${DOZZLE_WEB_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_APPDATA_ROOT}/dozzle:/data
    environment:
      - TZ=${TZ}
      - DOZZLE_ENABLE_ACTIONS=true
      - DOZZLE_ENABLE_SHELL=true
