services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: ${ADGUARDHOME_IP}
    ports:
      # Plain DNS
      - 53:53/tcp
      - 53:53/udp

      # DHCP
      #- 67:67/udp
      #- 68:68/udp

      # DNS-over-HTTPs
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp

      # DNS-over-TLS
      - 853:853/tcp

      # DNS-over-QUIC
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp

      # Admin Panel
      - 3000:3000/tcp

      # DNSCrypt
      #- 5443:5443/tcp
      #- 5443:5443/udp
    volumes:
      - ${DOCKER_APPDATA_ROOT}/adguardhome/conf:/opt/adguardhome/conf
      - ${DOCKER_APPDATA_ROOT}/adguardhome/work:/opt/adguardhome/work
      #- ${DOCKER_APPDATA_ROOT}/shared/certs/example.com:/certs

networks:
  default:
    driver: bridge
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE}
    ipam:
      config:
        - subnet: "${NETWORK_SUBNET}"
          ip_range: "${ADGUARDHOME_IP}/32"
          gateway: "${NETWORK_ROUTER_IP}"