services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:11.22.0@sha256:f24115c115f98a1cd69fea620bf20180be17889e9ae3c58ceabf5df1bc56c2a8
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=${ZWAVE_SESSION_SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=${TZ}
    networks:
      - zwave
    devices:
      - '${ZWAVE_DEVICE}:/dev/zwave'
    volumes:
      - ${DOCKER_APPDATA_ROOT}/zwave:/usr/src/app/store
    ports:
      - '${ZWAVE_WEB_PORT}:8091'
      - '${ZWAVE_WS_PORT}:3000'
networks:
  zwave:
