services:
  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:11.22.3@sha256:14d018bb689eecce4029229764d2191d9b8d8f211106fcabaef421e7b0f8cf9c
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=${ZWAVE_SESSION_SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=${TZ}
    networks:
      - zwave
    devices:
      - '${ZWAVE_DEVICE}:/dev/zwave'
    volumes:
      - ${DOCKER_APPDATA_ROOT}/zwave:/usr/src/app/store
    ports:
      - '${ZWAVE_WEB_PORT}:8091'
      - '${ZWAVE_WS_PORT}:3000'
networks:
  zwave:
