# Adapted from https://downloads.filestash.app/latest/docker-compose.yml
services:
  app:
    container_name: filestash
    image: machines/filestash:latest
    restart: unless-stopped
    environment:
    - APPLICATION_URL=
    - CANARY=true
    - OFFICE_URL=http://wopi_server:9980
    - OFFICE_REWRITE_URL=https://${FILES_OFFICE_FQDN}
    - OFFICE_FILESTASH_URL=https://${FILES_FQDN}
    ports:
    - "${FILES_HTTP_PORT}:8334"
    volumes:
    - ${DOCKER_APPDATA_ROOT}/filestash:/app/data/state/

  wopi_server:
    container_name: filestash_wopi
    image: collabora/code:24.04.10.2.1
    restart: unless-stopped
    environment:
    - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    - server_name=${FILES_OFFICE_FQDN}
    - aliasgroup1="https://.*:443"
    command:
    - /bin/bash
    - -c
    - |
         curl -o /usr/share/coolwsd/browser/dist/branding-desktop.css https://gist.githubusercontent.com/mickael-kerjean/bc1f57cd312cf04731d30185cc4e7ba2/raw/d706dcdf23c21441e5af289d871b33defc2770ea/destop.css
         /bin/su -s /bin/bash -c '/start-collabora-online.sh' cool
    user: root
    ports:
    - "${FILES_OFFICE_HTTP_PORT}:9980"
