services:
  caddy:
    container_name: caddy
    image: caddy:2.11.3@sha256:a464e5c4fb9c324b53adca428a40a66631e59127153b8816fab58103817ba8f0
    # Use "always" instead of "unless-stopped" so the reverse proxy
    # is never accidentally left down after a reboot.
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${DOCKER_APPDATA_ROOT}/caddy/data:/data
      - ${DOCKER_APPDATA_ROOT}/caddy/config:/config
    environment:
      - TZ=${TZ}
