services:
  caddy:
    container_name: caddy
    image: caddy:2.11.4@sha256:cfeb0b281bc44a5a51fecde39e9e577c60d863c0b6196e6bbdf58fd00960887f
    # Use "always" instead of "unless-stopped" so the reverse proxy
    # is never accidentally left down after a reboot.
    restart: always
    network_mode: host
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ${DOCKER_APPDATA_ROOT}/caddy/data:/data
      - ${DOCKER_APPDATA_ROOT}/caddy/config:/config
    environment:
      - TZ=${TZ}
