services:
  reverse-proxy:
    container_name: reverse-proxy
    image: ${DOCKER_REGISTRY}/reverse-proxy:latest
    restart: always
    tty: true
    environment:
      - ASPNETCORE_HTTP_PORTS=${REVERSE_PROXY_HTTP_PORT}
      - ASPNETCORE_HTTPS_PORTS=${REVERSE_PROXY_HTTPS_PORT}
      - REVERSE_PROXY_CONFIG_FILE=/etc/opt/reverse-proxy/reverse-proxy.json
      - REVERSE_PROXY_CERTIFICATE_DIRECTORY=/certs
    volumes:
      - ${DOCKER_APPDATA_ROOT}/reverse-proxy:/etc/opt/reverse-proxy
      - ${DOCKER_APPDATA_ROOT}/shared/certs:/certs
    ports:
      - '${REVERSE_PROXY_HTTP_PORT}:${REVERSE_PROXY_HTTP_PORT}'
      - '${REVERSE_PROXY_HTTPS_PORT}:${REVERSE_PROXY_HTTPS_PORT}'
