services:
  rclone:
    container_name: backup-rclone
    restart: unless-stopped
    tty: true
    environment:
      - TZ=${TZ}
      - BACKUP_TARGETS=${BACKUP_TARGETS}
    volumes:
      - ${DOCKER_APPDATA_ROOT}/backup/rclone:/config/rclone:rw
      - ${BACKUP_DATA_ROOT}:/data:ro
    build: .
