services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:12.0@sha256:baba630419915985442f315f08b0cf46d9f4c8a0cc4bd38e94a6d35751dd5ef5
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA_ROOT}/jellyfin/config:/config
      - ${DOCKER_APPDATA_ROOT}/jellyfin/cache:/cache
      - ${JELLYFIN_MEDIA_LOCATION}/Movies:/movies
      - ${JELLYFIN_MEDIA_LOCATION}/TV:/shows
      - ${JELLYFIN_MEDIA_LOCATION}/Music:/music
    devices:
      - /dev/dri:/dev/dri
    ports:
      - '${JELLYFIN_HTTP_PORT}:8096'
      - '${JELLYFIN_CLIENT_DISCOVERY_PORT}:7359'
