services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:10.11.11@sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    volumes:
      - ${DOCKER_APPDATA_ROOT}/jellyfin/config:/config
      - ${DOCKER_APPDATA_ROOT}/jellyfin/cache:/cache
      - ${JELLYFIN_MEDIA_LOCATION}/Movies:/movies
      - ${JELLYFIN_MEDIA_LOCATION}/TV:/shows
      - ${JELLYFIN_MEDIA_LOCATION}/Music:/music
    devices:
      - /dev/dri:/dev/dri
    ports:
      - '${JELLYFIN_HTTP_PORT}:8096'
      - '${JELLYFIN_CLIENT_DISCOVERY_PORT}:7359'
