services:
  webhook:
    container_name: webhook
    build:
      context: ../..
      dockerfile: services/webhook/Dockerfile
    restart: always
    ports:
      - "${WEBHOOK_HTTP_PORT}:9000"
    volumes:
      - ${CONFIG_DIR}:/config/env:ro
      - ${DEPLOY_KEY_PATH}:/config/deploy_key:ro
      - /etc/homelab.env:/etc/homelab.env:ro
    environment:
      - TZ=${TZ}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - DEPLOY_KEY_PATH=/config/deploy_key
      - CONFIG_DIR=/config/env
    command: ["-template", "-hooks", "/opt/homelab/hooks.json", "-verbose"]
