services:
  beszel:
    container_name: beszel
    image: henrygd/beszel:0.18.7@sha256:a849ad80814b6a1a3be665304dcace5d4854b3bed7bde4dd1227e8ce1b82d477
    restart: unless-stopped
    ports:
      - "${BESZEL_WEB_PORT}:8090"
    volumes:
      - ${DOCKER_APPDATA_ROOT}/beszel:/beszel_data
    environment:
      - TZ=${TZ}

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2.3.2@sha256:9aeb4e51d038047f414309c77a1af553281ca535723cb88907d907269d0a908e
    restart: unless-stopped
    ports:
      - "${UPTIME_KUMA_WEB_PORT}:3001"
    volumes:
      - ${DOCKER_APPDATA_ROOT}/uptime-kuma:/app/data
    environment:
      - TZ=${TZ}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
